"""squashed baseline schema

Revision ID: 077c06b272a1
Revises: 
Create Date: 2026-07-09 21:57:16.837041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '077c06b272a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 启用 pgvector 扩展（document_chunk.embedding 依赖 vector 类型，须先于建表）
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('collection_name', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_chunk_id', sa.String(length=128), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=False),
    sa.Column('text_search', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunk_chunk_id'), 'document_chunk', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_document_chunk_collection_name'), 'document_chunk', ['collection_name'], unique=False)
    op.create_index('ix_document_chunk_doc_id', 'document_chunk', ['doc_id'], unique=False)
    op.create_index('ix_document_chunk_is_parent', 'document_chunk', ['is_parent'], unique=False)
    op.create_index('ix_document_chunk_parent', 'document_chunk', ['parent_chunk_id'], unique=False)
    op.create_index('ix_document_chunk_text_search', 'document_chunk', ['text_search'], unique=False, postgresql_using='gin')
    op.create_index('ix_document_chunk_embedding_hnsw', 'document_chunk', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': 16, 'ef_construction': 200})
    op.create_index('ix_document_chunk_user_id', 'document_chunk', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_user_id'), 'chat_session', ['user_id'], unique=False)
    op.create_table('email_verification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_token_hash'), 'email_verification', ['token_hash'], unique=False)
    op.create_index('ix_email_verification_user_id', 'email_verification', ['user_id'], unique=False)
    op.create_table('generation_batch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kp_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('resource_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_batch_user_id'), 'generation_batch', ['user_id'], unique=False)
    op.create_table('kg_build_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('nodes_count', sa.Integer(), nullable=False),
    sa.Column('edges_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kg_build_task_doc_id', 'kg_build_task', ['doc_id'], unique=False)
    op.create_index('ix_kg_build_task_user_id', 'kg_build_task', ['user_id'], unique=False)
    op.create_table('kg_node',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kg_node_user_id', 'kg_node', ['user_id'], unique=False)
    op.create_index('ix_kg_node_user_type', 'kg_node', ['user_id', 'node_type'], unique=False)
    op.create_table('learning_path',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_user_id'), 'learning_path', ['user_id'], unique=False)
    op.create_table('resource_meta',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('kp_id', sa.String(length=256), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_meta_kp_id', 'resource_meta', ['kp_id'], unique=False)
    op.create_index('ix_resource_meta_user_id', 'resource_meta', ['user_id'], unique=False)
    op.create_index('ix_resource_meta_user_kp', 'resource_meta', ['user_id', 'kp_id'], unique=False)
    op.create_index('ix_resource_meta_user_type', 'resource_meta', ['user_id', 'resource_type'], unique=False)
    op.create_table('student_profile',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('cognitive_style', sa.String(length=32), nullable=True),
    sa.Column('daily_time_minutes', sa.Integer(), nullable=True),
    sa.Column('knowledge_mastered', sa.JSON(), nullable=True),
    sa.Column('knowledge_weak', sa.JSON(), nullable=True),
    sa.Column('error_prone', sa.JSON(), nullable=True),
    sa.Column('current_progress', sa.Text(), nullable=True),
    sa.Column('goal_questions', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('study_plan',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('daily_time_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source_path_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_plan_user_id', 'study_plan', ['user_id'], unique=False)
    op.create_index('ix_study_plan_user_status', 'study_plan', ['user_id', 'status'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=16), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.create_index('ix_chat_message_session_time', 'chat_message', ['session_id', 'created_at'], unique=False)
    op.create_table('generation_task',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['generation_batch.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_meta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_index(op.f('ix_generation_task_batch_id'), 'generation_task', ['batch_id'], unique=False)
    op.create_table('kg_edge',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['kg_node.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['kg_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relation')
    )
    op.create_table('learning_path_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('path_id', sa.BigInteger(), nullable=False),
    sa.Column('kp_id', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['kg_node.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['learning_path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_path_item_path_id'), 'learning_path_item', ['path_id'], unique=False)
    op.create_table('learning_record',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=True),
    sa.Column('kp_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['kg_node.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_meta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_record_kp_id', 'learning_record', ['kp_id'], unique=False)
    op.create_index('ix_learning_record_user_id', 'learning_record', ['user_id'], unique=False)
    op.create_index('ix_learning_record_user_kp', 'learning_record', ['user_id', 'kp_id'], unique=False)
    op.create_table('profile_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_history_profile_id'), 'profile_history', ['profile_id'], unique=False)
    op.create_table('quiz_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('resource_id', sa.BigInteger(), nullable=False),
    sa.Column('kp_id', sa.String(length=64), nullable=True),
    sa.Column('question_type', sa.String(length=16), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_item_resource_id'), 'quiz_item', ['resource_id'], unique=False)
    op.create_table('study_plan_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('plan_id', sa.BigInteger(), nullable=False),
    sa.Column('kp_id', sa.String(length=64), nullable=True),
    sa.Column('kp_name', sa.String(length=256), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=True),
    sa.Column('end_time', sa.String(length=5), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('resource_ids', sa.JSON(), nullable=True),
    sa.Column('missing_resource_types', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kp_id'], ['kg_node.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['study_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_study_plan_item_plan_date', 'study_plan_item', ['plan_id', 'scheduled_date'], unique=False)
    op.create_index('ix_study_plan_item_plan_id', 'study_plan_item', ['plan_id'], unique=False)
    op.create_table('quiz_attempt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('quiz_item_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('kp_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_item_id'], ['quiz_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_quiz_attempt_quiz_item_id', 'quiz_attempt', ['quiz_item_id'], unique=False)
    op.create_index('ix_quiz_attempt_user_id', 'quiz_attempt', ['user_id'], unique=False)
    op.create_index('ix_quiz_attempt_user_time', 'quiz_attempt', ['user_id', 'submitted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quiz_attempt_user_time', table_name='quiz_attempt')
    op.drop_index('ix_quiz_attempt_user_id', table_name='quiz_attempt')
    op.drop_index('ix_quiz_attempt_quiz_item_id', table_name='quiz_attempt')
    op.drop_table('quiz_attempt')
    op.drop_index('ix_study_plan_item_plan_id', table_name='study_plan_item')
    op.drop_index('ix_study_plan_item_plan_date', table_name='study_plan_item')
    op.drop_table('study_plan_item')
    op.drop_index(op.f('ix_quiz_item_resource_id'), table_name='quiz_item')
    op.drop_table('quiz_item')
    op.drop_index(op.f('ix_profile_history_profile_id'), table_name='profile_history')
    op.drop_table('profile_history')
    op.drop_index('ix_learning_record_user_kp', table_name='learning_record')
    op.drop_index('ix_learning_record_user_id', table_name='learning_record')
    op.drop_index('ix_learning_record_kp_id', table_name='learning_record')
    op.drop_table('learning_record')
    op.drop_index(op.f('ix_learning_path_item_path_id'), table_name='learning_path_item')
    op.drop_table('learning_path_item')
    op.drop_table('kg_edge')
    op.drop_index(op.f('ix_generation_task_batch_id'), table_name='generation_task')
    op.drop_table('generation_task')
    op.drop_index('ix_chat_message_session_time', table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index('ix_study_plan_user_status', table_name='study_plan')
    op.drop_index('ix_study_plan_user_id', table_name='study_plan')
    op.drop_table('study_plan')
    op.drop_table('student_profile')
    op.drop_index('ix_resource_meta_user_type', table_name='resource_meta')
    op.drop_index('ix_resource_meta_user_kp', table_name='resource_meta')
    op.drop_index('ix_resource_meta_user_id', table_name='resource_meta')
    op.drop_index('ix_resource_meta_kp_id', table_name='resource_meta')
    op.drop_table('resource_meta')
    op.drop_index(op.f('ix_learning_path_user_id'), table_name='learning_path')
    op.drop_table('learning_path')
    op.drop_index('ix_kg_node_user_type', table_name='kg_node')
    op.drop_index('ix_kg_node_user_id', table_name='kg_node')
    op.drop_table('kg_node')
    op.drop_index('ix_kg_build_task_user_id', table_name='kg_build_task')
    op.drop_index('ix_kg_build_task_doc_id', table_name='kg_build_task')
    op.drop_table('kg_build_task')
    op.drop_index(op.f('ix_generation_batch_user_id'), table_name='generation_batch')
    op.drop_table('generation_batch')
    op.drop_index('ix_email_verification_user_id', table_name='email_verification')
    op.drop_index(op.f('ix_email_verification_token_hash'), table_name='email_verification')
    op.drop_table('email_verification')
    op.drop_index(op.f('ix_chat_session_user_id'), table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_table('user')
    op.drop_index('ix_document_chunk_user_id', table_name='document_chunk')
    op.drop_index('ix_document_chunk_embedding_hnsw', table_name='document_chunk', postgresql_using='hnsw')
    op.drop_index('ix_document_chunk_text_search', table_name='document_chunk', postgresql_using='gin')
    op.drop_index('ix_document_chunk_parent', table_name='document_chunk')
    op.drop_index('ix_document_chunk_is_parent', table_name='document_chunk')
    op.drop_index('ix_document_chunk_doc_id', table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_collection_name'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_chunk_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
