"""add_extra_to_chat_message

Revision ID: 13c01e0c4c91
Revises: b2c3d4e5f6a7
Create Date: 2026-05-31 16:49:59.069440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13c01e0c4c91'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_eval_analysis_created_at'), table_name='rag_eval_analysis')
    op.drop_index(op.f('ix_rag_eval_analysis_type'), table_name='rag_eval_analysis')
    op.drop_table('rag_eval_analysis')
    op.drop_index(op.f('ix_rag_eval_result_agent_type'), table_name='rag_eval_result')
    op.drop_index(op.f('ix_rag_eval_result_created_at'), table_name='rag_eval_result')
    op.drop_index(op.f('ix_rag_eval_result_experiment_group'), table_name='rag_eval_result')
    op.drop_index(op.f('ix_rag_eval_result_session_id'), table_name='rag_eval_result')
    op.drop_table('rag_eval_result')
    op.add_column('chat_message', sa.Column('extra', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('chat_session_user_id_fkey'), 'chat_session', type_='foreignkey')
    op.create_foreign_key(None, 'chat_session', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('document_chunk_chunk_id_key'), 'document_chunk', type_='unique')
    op.drop_index(op.f('ix_document_chunk_doc_id_hash'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_embedding_hnsw'), table_name='document_chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_document_chunk_metadata'), table_name='document_chunk', postgresql_using='gin')
    op.drop_index(op.f('ix_document_chunk_chunk_id'), table_name='document_chunk')
    op.create_index(op.f('ix_document_chunk_chunk_id'), 'document_chunk', ['chunk_id'], unique=True)
    op.drop_column('document_chunk', 'content_hash')
    op.drop_constraint(op.f('generation_batch_user_id_fkey'), 'generation_batch', type_='foreignkey')
    op.create_foreign_key(None, 'generation_batch', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('generation_task_batch_id_fkey'), 'generation_task', type_='foreignkey')
    op.drop_constraint(op.f('generation_task_resource_id_fkey'), 'generation_task', type_='foreignkey')
    op.create_foreign_key(None, 'generation_task', 'resource_meta', ['resource_id'], ['id'])
    op.create_foreign_key(None, 'generation_task', 'generation_batch', ['batch_id'], ['id'])
    op.drop_constraint(op.f('kg_build_task_user_id_fkey'), 'kg_build_task', type_='foreignkey')
    op.create_foreign_key(None, 'kg_build_task', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('kg_edge_target_id_fkey'), 'kg_edge', type_='foreignkey')
    op.drop_constraint(op.f('kg_edge_source_id_fkey'), 'kg_edge', type_='foreignkey')
    op.create_foreign_key(None, 'kg_edge', 'kg_node', ['target_id'], ['id'])
    op.create_foreign_key(None, 'kg_edge', 'kg_node', ['source_id'], ['id'])
    op.drop_constraint(op.f('kg_node_user_id_fkey'), 'kg_node', type_='foreignkey')
    op.create_foreign_key(None, 'kg_node', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('learning_path_user_id_fkey'), 'learning_path', type_='foreignkey')
    op.create_foreign_key(None, 'learning_path', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('learning_path_item_path_id_fkey'), 'learning_path_item', type_='foreignkey')
    op.drop_constraint(op.f('learning_path_item_kp_id_fkey'), 'learning_path_item', type_='foreignkey')
    op.create_foreign_key(None, 'learning_path_item', 'learning_path', ['path_id'], ['id'])
    op.create_foreign_key(None, 'learning_path_item', 'kg_node', ['kp_id'], ['id'])
    op.drop_constraint(op.f('learning_record_resource_id_fkey'), 'learning_record', type_='foreignkey')
    op.drop_constraint(op.f('learning_record_user_id_fkey'), 'learning_record', type_='foreignkey')
    op.drop_constraint(op.f('learning_record_kp_id_fkey'), 'learning_record', type_='foreignkey')
    op.create_foreign_key(None, 'learning_record', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'learning_record', 'resource_meta', ['resource_id'], ['id'])
    op.create_foreign_key(None, 'learning_record', 'kg_node', ['kp_id'], ['id'])
    op.drop_constraint(op.f('profile_history_profile_id_fkey'), 'profile_history', type_='foreignkey')
    op.create_foreign_key(None, 'profile_history', 'student_profile', ['profile_id'], ['id'])
    op.drop_constraint(op.f('quiz_attempt_user_id_fkey'), 'quiz_attempt', type_='foreignkey')
    op.drop_constraint(op.f('quiz_attempt_quiz_item_id_fkey'), 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_attempt', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'quiz_attempt', 'quiz_item', ['quiz_item_id'], ['id'])
    op.drop_constraint(op.f('quiz_item_resource_id_fkey'), 'quiz_item', type_='foreignkey')
    op.create_foreign_key(None, 'quiz_item', 'resource_meta', ['resource_id'], ['id'])
    op.drop_constraint(op.f('resource_meta_user_id_fkey'), 'resource_meta', type_='foreignkey')
    op.create_foreign_key(None, 'resource_meta', 'user', ['user_id'], ['id'])
    op.drop_constraint(op.f('student_profile_user_id_fkey'), 'student_profile', type_='foreignkey')
    op.create_foreign_key(None, 'student_profile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_profile', type_='foreignkey')
    op.create_foreign_key(op.f('student_profile_user_id_fkey'), 'student_profile', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'resource_meta', type_='foreignkey')
    op.create_foreign_key(op.f('resource_meta_user_id_fkey'), 'resource_meta', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'quiz_item', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_item_resource_id_fkey'), 'quiz_item', 'resource_meta', ['resource_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempt', type_='foreignkey')
    op.create_foreign_key(op.f('quiz_attempt_quiz_item_id_fkey'), 'quiz_attempt', 'quiz_item', ['quiz_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('quiz_attempt_user_id_fkey'), 'quiz_attempt', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'profile_history', type_='foreignkey')
    op.create_foreign_key(op.f('profile_history_profile_id_fkey'), 'profile_history', 'student_profile', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'learning_record', type_='foreignkey')
    op.drop_constraint(None, 'learning_record', type_='foreignkey')
    op.drop_constraint(None, 'learning_record', type_='foreignkey')
    op.create_foreign_key(op.f('learning_record_kp_id_fkey'), 'learning_record', 'kg_node', ['kp_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('learning_record_user_id_fkey'), 'learning_record', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('learning_record_resource_id_fkey'), 'learning_record', 'resource_meta', ['resource_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'learning_path_item', type_='foreignkey')
    op.drop_constraint(None, 'learning_path_item', type_='foreignkey')
    op.create_foreign_key(op.f('learning_path_item_kp_id_fkey'), 'learning_path_item', 'kg_node', ['kp_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('learning_path_item_path_id_fkey'), 'learning_path_item', 'learning_path', ['path_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'learning_path', type_='foreignkey')
    op.create_foreign_key(op.f('learning_path_user_id_fkey'), 'learning_path', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'kg_node', type_='foreignkey')
    op.create_foreign_key(op.f('kg_node_user_id_fkey'), 'kg_node', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'kg_edge', type_='foreignkey')
    op.drop_constraint(None, 'kg_edge', type_='foreignkey')
    op.create_foreign_key(op.f('kg_edge_source_id_fkey'), 'kg_edge', 'kg_node', ['source_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('kg_edge_target_id_fkey'), 'kg_edge', 'kg_node', ['target_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'kg_build_task', type_='foreignkey')
    op.create_foreign_key(op.f('kg_build_task_user_id_fkey'), 'kg_build_task', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'generation_task', type_='foreignkey')
    op.drop_constraint(None, 'generation_task', type_='foreignkey')
    op.create_foreign_key(op.f('generation_task_resource_id_fkey'), 'generation_task', 'resource_meta', ['resource_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('generation_task_batch_id_fkey'), 'generation_task', 'generation_batch', ['batch_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'generation_batch', type_='foreignkey')
    op.create_foreign_key(op.f('generation_batch_user_id_fkey'), 'generation_batch', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('document_chunk', sa.Column('content_hash', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_chunk_chunk_id'), table_name='document_chunk')
    op.create_index(op.f('ix_document_chunk_chunk_id'), 'document_chunk', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunk_metadata'), 'document_chunk', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_document_chunk_embedding_hnsw'), 'document_chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '200'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_document_chunk_doc_id_hash'), 'document_chunk', ['doc_id', 'content_hash'], unique=False)
    op.create_unique_constraint(op.f('document_chunk_chunk_id_key'), 'document_chunk', ['chunk_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.create_foreign_key(op.f('chat_session_user_id_fkey'), 'chat_session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chat_message', 'extra')
    op.create_table('rag_eval_result',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=64), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('agent_type', sa.VARCHAR(length=32), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('kp_name', sa.VARCHAR(length=512), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('experiment_group', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('n_retrieved', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('n_candidates', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('scores_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scores_p50', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scores_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('embedding_latency_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('db_query_latency_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('relevance_labels', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('precision_at_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recall_at_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ndcg_at_5', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('faithfulness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hallucination_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('completeness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('citation_precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cross_validated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('cross_validation_disagreement', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_eval_result_pkey'))
    )
    op.create_index(op.f('ix_rag_eval_result_session_id'), 'rag_eval_result', ['session_id'], unique=False)
    op.create_index(op.f('ix_rag_eval_result_experiment_group'), 'rag_eval_result', ['experiment_group'], unique=False)
    op.create_index(op.f('ix_rag_eval_result_created_at'), 'rag_eval_result', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_eval_result_agent_type'), 'rag_eval_result', ['agent_type'], unique=False)
    op.create_table('rag_eval_analysis',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(length=32), server_default=sa.text("'golden_run'::character varying"), autoincrement=False, nullable=True),
    sa.Column('source_reference', sa.VARCHAR(length=512), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('avg_faithfulness', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('avg_completeness', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('avg_precision_at_5', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('pass_rate', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('total_queries', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('bottlenecks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('suggestions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('key_findings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('per_kp_breakdown', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trend', sa.VARCHAR(length=32), server_default=sa.text("'stable'::character varying"), autoincrement=False, nullable=True),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('rag_eval_analysis_pkey'))
    )
    op.create_index(op.f('ix_rag_eval_analysis_type'), 'rag_eval_analysis', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_rag_eval_analysis_created_at'), 'rag_eval_analysis', ['created_at'], unique=False)
    # ### end Alembic commands ###
