"""add_document_chunk

Revision ID: 9069c06f0251
Revises: a6844ed9ad28
Create Date: 2026-05-15 14:46:14.087854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9069c06f0251'
down_revision: Union[str, Sequence[str], None] = 'a6844ed9ad28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.String(length=128), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('collection_name', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunk_chunk_id'), 'document_chunk', ['chunk_id'], unique=True)
    op.create_index(op.f('ix_document_chunk_collection_name'), 'document_chunk', ['collection_name'], unique=False)
    op.create_index(op.f('ix_document_chunk_doc_id'), 'document_chunk', ['doc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunk_doc_id'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_collection_name'), table_name='document_chunk')
    op.drop_index(op.f('ix_document_chunk_chunk_id'), table_name='document_chunk')
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
