"""initial_schema

Revision ID: a6844ed9ad28
Revises: 
Create Date: 2026-05-15 14:13:01.393402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6844ed9ad28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('messages_table', sa.String(length=128), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('resource_types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kg_build_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('doc_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('nodes_count', sa.Integer(), nullable=False),
    sa.Column('edges_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kg_node',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('node_type', sa.Enum('Course', 'Chapter', 'KnowledgePoint', 'SubPoint', 'Concept', name='kgnodetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('course_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_path',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_meta',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.String(length=256), nullable=False),
    sa.Column('resource_type', sa.Enum('doc', 'mindmap', 'quiz', 'code', 'summary', 'kg', name='resourcetype'), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('major', sa.String(length=128), nullable=True),
    sa.Column('learning_goal', sa.Text(), nullable=True),
    sa.Column('cognitive_style', sa.Enum('视觉型', '阅读型', '动手型', name='cognitivestyle'), nullable=True),
    sa.Column('daily_time_minutes', sa.Integer(), nullable=True),
    sa.Column('knowledge_mastered', sa.JSON(), nullable=True),
    sa.Column('knowledge_weak', sa.JSON(), nullable=True),
    sa.Column('error_prone', sa.JSON(), nullable=True),
    sa.Column('current_progress', sa.Text(), nullable=True),
    sa.Column('goal_questions', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.create_index('ix_chat_message_session_time', 'chat_message', ['session_id', 'created_at'], unique=False)
    op.create_table('generation_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['generation_batch.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_meta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_table('kg_edge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('relation', sa.Enum('IS_PART_OF', 'REQUIRES', 'RELATED_TO', 'CONTAINS', name='kgrelation'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['kg_node.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['kg_node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relation')
    )
    op.create_table('learning_path_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('path_id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['kg_node.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['learning_path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('kp_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['kg_node.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_meta.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.String(length=64), nullable=True),
    sa.Column('question_type', sa.Enum('single', 'multi', 'fill', 'short', name='questiontype'), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quiz_item_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('kp_id', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_item_id'], ['quiz_item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_attempt')
    op.drop_table('quiz_item')
    op.drop_table('profile_history')
    op.drop_table('learning_record')
    op.drop_table('learning_path_item')
    op.drop_table('kg_edge')
    op.drop_table('generation_task')
    op.drop_index('ix_chat_message_session_time', table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_table('student_profile')
    op.drop_table('resource_meta')
    op.drop_table('learning_path')
    op.drop_table('kg_node')
    op.drop_table('kg_build_task')
    op.drop_table('generation_batch')
    op.drop_table('chat_session')
    op.drop_table('user')
    # ### end Alembic commands ###
